development:
  password: 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
  theme_id: "115425902751"
  store: apptestfw.myshopify.com
  ignore_files:
  - node_modules
  - config/settings_data.json
  - pictures
  - product-scvs-master